language: python
python:
  - "2.6"
  - "2.7"
sudo: required
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "sudo apt-get install python-pygame"
# command to run tests
script: "python -m doctest -v OctoPiControlPanel.py"